### ISSUE TITLE
Desenvolver sistema de led usando LDR

### ISSUE THREAD

**Issue by FlorSousa** [neuron-byte/open-ino#1]
Desenvolver um circuito usando um resistor baseado em luz que acenda quando estiver escuro e apague quando estiver claro. Terminar até a próxima reunião e mostrar na reunião

**Comment by M1gu3lDev** [comment]
![Image](https://github.com/neuron-byte/open-ino/assets/140343469/e34ae429-d04e-43bd-adcc-d162e6a5016c)

/ C++ code
#define LED 12
#define LDR A0
void setup()
{
  pinMode(LED, OUTPUT);
  pinMode(LDR, INPUT);
}

void loop()
{
  if (analogRead(LDR)>900){
  	digitalWrite(LED, LOW);
  }
  
  else{
    digitalWrite(LED, HIGH);
  }
 
}
